name: Deployment

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: web
    runs-on: ubuntu-latest

    steps:
      - name: chekout repo
        uses: actions/checkout@v4

      - name: Setup node js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: apps/web

      - name: build project
        run: pnpm build
        shell: bash
        working-directory: apps/web
        env:
          VITE_API_URL: /api

  api:
    name: api
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME: ghcr.io/rajandhamala/codoodle-api
      CONTAINER_NAME: codoole-api

    steps:
      - name: chekout repo
        uses: actions/checkout@v4

      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: apps/api
